### ISSUE TITLE
docker compose doesn't launch a server

### ISSUE THREAD

**Issue by elizabethyalkut** [Brown-University-Library/sr_public_webapp_project#1]
When I clone this repo and cd in to run Docker, I get the following error:
```
12:32:00 in sr_public_webapp on  main on 🐳 v24.0.2
🔋⇣100% 🚀 ➜ docker compose up
[+] Building 0.2s (3/3) FINISHED
 => [web internal] load build definition from Dockerfile                   0.0s
 => => transferring dockerfile: 553B                                       0.0s
 => [web internal] load .dockerignore                                      0.0s
 => => transferring context: 2B                                            0.0s
 => ERROR [web internal] load metadata for docker.io/library/python:3.8    0.2s
------
 > [web internal] load metadata for docker.io/library/python:3.8:
------
failed to solve: python:3.8: error getting credentials - err: docker-credential-desktop resolves to executable in current directory (./docker-credential-desktop), out: ``
```

**Comment by birkin** [comment]
@elizabethyalkut

- I'm thinking that docker is having trouble loading python3.8, [here](https://github.com/Brown-University-Library/sr_public_webapp_project/blob/d5960db6c3a5e97e6cdaca10db04dc8c47757b39/Dockerfile#L4), which is strange because it's a standard dockerhub location...
- I consulted the new-oracle, which offered [some suggestions](https://chat.openai.com/share/b6c47efc-6741-441f-adf6-b789c891e569).  🤞
- pinging @ccarvel, who's more docker-knowledgeable.

**Comment by birkin** [comment]
oh, also, i did fully delete my container and image and fully re-installed it, and it does work for me. hmm...

**Comment by birkin** [comment]
i also deleted my python3.8 image, and ran `docker system prune` to ensure i'm deleting all sorts of cache and unused stuff, and re-ran the `docker-compose up` command -- and all works.  🤔

**Comment by birkin** [comment]
just thought of a workaround if debugging is a hassle...

- you could make a branch
- change the dockerfile python version specification to 3.9 -- which docker likely already can access because it's used for the sr-data-entry-form [here](https://github.com/Brown-University-Library/disa_dj_project/blob/acec5adca321378de06eaabed612c66124a63659/Dockerfile.dev#L4)
- ...and then try `docker-compose up` again after crossing your fingers and clicking your heels together three times.

fyi -- i like using newer versions of python -- but our servers use python3.8, so I usually specify that version.

**Comment by elizabethyalkut** [comment]
Reinstalling docker (with brew) did the trick! Why? It's a mystery.
